### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by HLFH** [aeris/cryptcheck#63]
Hello @aeris, 

Tools like [Hardenize](https://www.hardenize.com/) that are not open source do well SMTP TLS checks.

We have to come to the conclusion the repo owner @aeris neither has yet the time nor the support from contributors to make Cryptcheck working again.

So I advise to archive this repo - and the Cryptcheck website - and eventually (or not) advise in the README to use other alternatives.

**Comment by aeris** [comment]
Cryptcheck perfectly works at the moment. Only some weird TLS behavior on some servers for unknown reasons hard to spot and debug occurs sometime but there is thousand of checking processed each day without troubles.
There is no major change in TLS ecosystem since the last CryptCheck change and so current scoring still accurate.
